FROM gradle:8.11.1-jdk17 AS build
WORKDIR /app

COPY build.gradle.kts settings.gradle.kts gradle.properties ./
COPY gradle ./gradle

RUN gradle build --no-daemon || return 0

COPY . .

RUN gradle :server:shadowJar --no-daemon

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

COPY --from=build /app/server/build/libs/server-all.jar app.jar

COPY .env .env

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
